version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: pg
      POSTGRES_DB: users
    ports:
      - 5432:5432
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
